name: vplanet
channels:
  - defaults
dependencies:
  - numpy>=1.19.2
  - pip>=20.3.3
  - scipy>=1.5.2
  - setuptools>=51.3.3
  - pip:
      - matplotlib>=3.3.3
      - nose>=1.3.7
      - parameterized>=0.8.1
      - pytest>=6.2.4
      - pytest-dependency>=0.5.1
      - pytest-env>=0.6.2
      - pytest-cov>=2.11.1
      - sphinx
      - sphinx-rtd-theme
      - breathe>=4.30.0
      - sphinxcontrib-bibtex>=2.2.0
      - coverage>=5.5
      - tqdm
      - pre-commit
      - clang-format
      - seaborn
